name: Publish Library to PyPI (MacOS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r requirements.txt

    - name: Build Python wheels
      run: |
        python setup.py bdist_wheel

    - name: Upload Python wheels as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: python-wheels
        path: dist/*.whl
