name: Build & Publish to PyPI

on:
  push:
    branches: [main]
  workflow_dispatch:

########################################################################
# 1 ── Check whether this exact version is already on PyPI ────────────#
########################################################################
jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      already_published: ${{ steps.check.outputs.already_published }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build-time deps for setup.py
      run: |
        python -m pip install --upgrade pip
        pip install numpy cython

    - name: Check if version exists on PyPI
      id: check
      run: |
        PACKAGE_NAME=$(python setup.py --name)
        PACKAGE_VERSION=$(python setup.py --version)
        echo "Package: ${PACKAGE_NAME}"
        echo "Version: ${PACKAGE_VERSION}"

        if curl --silent -f "https://pypi.org/project/${PACKAGE_NAME}/${PACKAGE_VERSION}/"; then
          echo "Version already on PyPI – skipping build."
          echo "already_published=true"  >> "$GITHUB_OUTPUT"
        else
          echo "Version not on PyPI – continue with build."
          echo "already_published=false" >> "$GITHUB_OUTPUT"
        fi

#######################################################################
# 2 ── Build wheels (Linux, macOS, Windows) + one sdist  ──────────────#
#######################################################################
  build:
    needs: check_version
    if: needs.check_version.outputs.already_published == 'false'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]

    steps:
    - uses: actions/checkout@v4

    # ── Build binary wheels with cibuildwheel ──
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.18
      with:
        package-dir: .
      env:
        # Which Python versions to build for
        CIBW_BUILD: "cp310-* cp311-* cp312-*"
        # Skip Alpine (musllinux) – drop if you want those too
        CIBW_SKIP: "*musllinux*"
        # Make sure build deps are present *before* compiling extensions
        # CIBW_BEFORE_BUILD: "pip install -U cython numpy"
        # # ─── KEY LINE: disable pip build-isolation ───
        # CIBW_ENVIRONMENT: "PIP_NO_BUILD_ISOLATION=1"

    # ── Build source distribution once (Linux) ──
    - name: Build sdist
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip setuptools wheel cython numpy
        python setup.py sdist --dist-dir wheelhouse

    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}
        path: wheelhouse/*

##################################################
# 3 ── Publish everything to PyPI in one go ─────#
##################################################
  publish:
    needs: [check_version, build]
    if: needs.check_version.outputs.already_published == 'false'
    runs-on: ubuntu-latest

    steps:
    - name: Download artefacts
      uses: actions/download-artifact@v4
      with:
        pattern: dist-*
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        packages-dir: dist
